// 생성물 (gen_aos_test.py): 엔진 aos 를 GPU 에서 (층 2)
#include "core/common/aos.h"
#include <cstring>
#include <cstdint>
#include <cuda_runtime.h>
using namespace eng::aos;
__device__ void aos_call(int fid, const float* in, float* out) {
  switch (fid) {
  case 0: { const QuatV r = QuatVLoadXYZW(in[0], in[4], in[8], in[12]); memcpy(out, &r, sizeof(r)); } break;
  case 1: { const Vec3V r = Vec3V_From_Vec4V(*(const Vec4V*)&in[0]); memcpy(out, &r, sizeof(r)); } break;
  case 2: { const Vec3V r = Vec3V_From_Vec4V_WUndefined(*(const Vec4V*)&in[0]); memcpy(out, &r, sizeof(r)); } break;
  case 3: { const Vec4V r = Vec4V_From_Vec3V(*(const Vec3V*)&in[0]); memcpy(out, &r, sizeof(r)); } break;
  case 4: { const Vec4V r = Vec4V_From_VecU32V(*(const VecU32V*)&in[0]); memcpy(out, &r, sizeof(r)); } break;
  case 5: { const Vec4V r = Vec4V_From_VecI32V(*(const VecI32V*)&in[0]); memcpy(out, &r, sizeof(r)); } break;
  case 6: { const VecU32V r = VecU32V_From_BoolV(*(const BoolV*)&in[0]); memcpy(out, &r, sizeof(r)); } break;
  case 7: { const VecI32V r = VecI32V_From_Vec4V(*(const Vec4V*)&in[0]); memcpy(out, &r, sizeof(r)); } break;
  case 8: { const float r = isFiniteFloatV(*(const FloatV*)&in[0]) ? 1.0f : 0.0f; memcpy(out, &r, 4); } break;
  case 9: { const float r = isFiniteVec3V(*(const Vec3V*)&in[0]) ? 1.0f : 0.0f; memcpy(out, &r, 4); } break;
  case 10: { const float r = isFiniteVec4V(*(const Vec4V*)&in[0]) ? 1.0f : 0.0f; memcpy(out, &r, 4); } break;
  case 11: { const float r = isValidVec3V(*(const Vec3V*)&in[0]) ? 1.0f : 0.0f; memcpy(out, &r, 4); } break;
  case 12: { const FloatV r0 = FZero(); const Vec4V r = r0; memcpy(out, &r, sizeof(r)); } break;
  case 13: { const FloatV r0 = FOne(); const Vec4V r = r0; memcpy(out, &r, sizeof(r)); } break;
  case 14: { const FloatV r0 = FHalf(); const Vec4V r = r0; memcpy(out, &r, sizeof(r)); } break;
  case 15: { const FloatV r0 = FEps(); const Vec4V r = r0; memcpy(out, &r, sizeof(r)); } break;
  case 16: { const FloatV r0 = FMax(); const Vec4V r = r0; memcpy(out, &r, sizeof(r)); } break;
  case 17: { const FloatV r0 = FNegMax(); const Vec4V r = r0; memcpy(out, &r, sizeof(r)); } break;
  case 18: { const FloatV r0 = FEps6(); const Vec4V r = r0; memcpy(out, &r, sizeof(r)); } break;
  case 19: { const FloatV r0 = FNeg(*(const FloatV*)&in[0]); const Vec4V r = r0; memcpy(out, &r, sizeof(r)); } break;
  case 20: { const FloatV r0 = FAdd(*(const FloatV*)&in[0], *(const FloatV*)&in[4]); const Vec4V r = r0; memcpy(out, &r, sizeof(r)); } break;
  case 21: { const FloatV r0 = FSub(*(const FloatV*)&in[0], *(const FloatV*)&in[4]); const Vec4V r = r0; memcpy(out, &r, sizeof(r)); } break;
  case 22: { const FloatV r0 = FMul(*(const FloatV*)&in[0], *(const FloatV*)&in[4]); const Vec4V r = r0; memcpy(out, &r, sizeof(r)); } break;
  case 23: { const FloatV r0 = FDiv(*(const FloatV*)&in[0], *(const FloatV*)&in[4]); const Vec4V r = r0; memcpy(out, &r, sizeof(r)); } break;
  case 24: { const FloatV r0 = FDivFast(*(const FloatV*)&in[0], *(const FloatV*)&in[4]); const Vec4V r = r0; memcpy(out, &r, sizeof(r)); } break;
  case 25: { const FloatV r0 = FRecip(*(const FloatV*)&in[0]); const Vec4V r = r0; memcpy(out, &r, sizeof(r)); } break;
  case 26: { const FloatV r0 = FRecipFast(*(const FloatV*)&in[0]); const Vec4V r = r0; memcpy(out, &r, sizeof(r)); } break;
  case 27: { const FloatV r0 = FRsqrt(*(const FloatV*)&in[0]); const Vec4V r = r0; memcpy(out, &r, sizeof(r)); } break;
  case 28: { const FloatV r0 = FRsqrtFast(*(const FloatV*)&in[0]); const Vec4V r = r0; memcpy(out, &r, sizeof(r)); } break;
  case 29: { const FloatV r0 = FSqrt(*(const FloatV*)&in[0]); const Vec4V r = r0; memcpy(out, &r, sizeof(r)); } break;
  case 30: { const FloatV r0 = FScaleAdd(*(const FloatV*)&in[0], *(const FloatV*)&in[4], *(const FloatV*)&in[8]); const Vec4V r = r0; memcpy(out, &r, sizeof(r)); } break;
  case 31: { const FloatV r0 = FNegScaleSub(*(const FloatV*)&in[0], *(const FloatV*)&in[4], *(const FloatV*)&in[8]); const Vec4V r = r0; memcpy(out, &r, sizeof(r)); } break;
  case 32: { const FloatV r0 = FAbs(*(const FloatV*)&in[0]); const Vec4V r = r0; memcpy(out, &r, sizeof(r)); } break;
  case 33: { const FloatV r0 = FSel(*(const BoolV*)&in[0], *(const FloatV*)&in[4], *(const FloatV*)&in[8]); const Vec4V r = r0; memcpy(out, &r, sizeof(r)); } break;
  case 34: { const BoolV r = FIsGrtr(*(const FloatV*)&in[0], *(const FloatV*)&in[4]); memcpy(out, &r, sizeof(r)); } break;
  case 35: { const BoolV r = FIsGrtrOrEq(*(const FloatV*)&in[0], *(const FloatV*)&in[4]); memcpy(out, &r, sizeof(r)); } break;
  case 36: { const BoolV r = FIsEq(*(const FloatV*)&in[0], *(const FloatV*)&in[4]); memcpy(out, &r, sizeof(r)); } break;
  case 37: { const FloatV r0 = FMin(*(const FloatV*)&in[0], *(const FloatV*)&in[4]); const Vec4V r = r0; memcpy(out, &r, sizeof(r)); } break;
  case 38: { const FloatV r0 = FClamp(*(const FloatV*)&in[0], *(const FloatV*)&in[4], *(const FloatV*)&in[8]); const Vec4V r = r0; memcpy(out, &r, sizeof(r)); } break;
  case 39: { const uint32_t r = FAllGrtr(*(const FloatV*)&in[0], *(const FloatV*)&in[4]); memcpy(out, &r, 4); } break;
  case 40: { const uint32_t r = FAllGrtrOrEq(*(const FloatV*)&in[0], *(const FloatV*)&in[4]); memcpy(out, &r, 4); } break;
  case 41: { const uint32_t r = FAllEq(*(const FloatV*)&in[0], *(const FloatV*)&in[4]); memcpy(out, &r, 4); } break;
  case 42: { const uint32_t r = FOutOfBounds(*(const FloatV*)&in[0], *(const FloatV*)&in[4], *(const FloatV*)&in[8]); memcpy(out, &r, 4); } break;
  case 43: { const uint32_t r = FInBounds(*(const FloatV*)&in[0], *(const FloatV*)&in[4], *(const FloatV*)&in[8]); memcpy(out, &r, 4); } break;
  case 44: { const FloatV r0 = FRound(*(const FloatV*)&in[0]); const Vec4V r = r0; memcpy(out, &r, sizeof(r)); } break;
  case 45: { const FloatV r0 = FSin(*(const FloatV*)&in[0]); const Vec4V r = r0; memcpy(out, &r, sizeof(r)); } break;
  case 46: { const FloatV r0 = FCos(*(const FloatV*)&in[0]); const Vec4V r = r0; memcpy(out, &r, sizeof(r)); } break;
  case 47: { const Vec3V r = V3Splat(*(const FloatV*)&in[0]); memcpy(out, &r, sizeof(r)); } break;
  case 48: { const Vec3V r = V3Merge(*(const FloatV*)&in[0], *(const FloatV*)&in[4], *(const FloatV*)&in[8]); memcpy(out, &r, sizeof(r)); } break;
  case 49: { const Vec3V r = V3UnitX(); memcpy(out, &r, sizeof(r)); } break;
  case 50: { const Vec3V r = V3UnitY(); memcpy(out, &r, sizeof(r)); } break;
  case 51: { const Vec3V r = V3UnitZ(); memcpy(out, &r, sizeof(r)); } break;
  case 52: { const FloatV r0 = V3GetX(*(const Vec3V*)&in[0]); const Vec4V r = r0; memcpy(out, &r, sizeof(r)); } break;
  case 53: { const FloatV r0 = V3GetY(*(const Vec3V*)&in[0]); const Vec4V r = r0; memcpy(out, &r, sizeof(r)); } break;
  case 54: { const FloatV r0 = V3GetZ(*(const Vec3V*)&in[0]); const Vec4V r = r0; memcpy(out, &r, sizeof(r)); } break;
  case 55: { const Vec3V r = V3SetX(*(const Vec3V*)&in[0], *(const FloatV*)&in[4]); memcpy(out, &r, sizeof(r)); } break;
  case 56: { const Vec3V r = V3SetY(*(const Vec3V*)&in[0], *(const FloatV*)&in[4]); memcpy(out, &r, sizeof(r)); } break;
  case 57: { const Vec3V r = V3SetZ(*(const Vec3V*)&in[0], *(const FloatV*)&in[4]); memcpy(out, &r, sizeof(r)); } break;
  case 58: { const float r = V3ReadX(*(const Vec3V*)&in[0]); memcpy(out, &r, 4); } break;
  case 59: { const float r = V3ReadY(*(const Vec3V*)&in[0]); memcpy(out, &r, 4); } break;
  case 60: { const float r = V3ReadZ(*(const Vec3V*)&in[0]); memcpy(out, &r, 4); } break;
  case 61: { const Vec3V r = V3ColX(*(const Vec3V*)&in[0], *(const Vec3V*)&in[4], *(const Vec3V*)&in[8]); memcpy(out, &r, sizeof(r)); } break;
  case 62: { const Vec3V r = V3ColY(*(const Vec3V*)&in[0], *(const Vec3V*)&in[4], *(const Vec3V*)&in[8]); memcpy(out, &r, sizeof(r)); } break;
  case 63: { const Vec3V r = V3ColZ(*(const Vec3V*)&in[0], *(const Vec3V*)&in[4], *(const Vec3V*)&in[8]); memcpy(out, &r, sizeof(r)); } break;
  case 64: { const Vec3V r = V3Zero(); memcpy(out, &r, sizeof(r)); } break;
  case 65: { const Vec3V r = V3One(); memcpy(out, &r, sizeof(r)); } break;
  case 66: { const Vec3V r = V3Eps(); memcpy(out, &r, sizeof(r)); } break;
  case 67: { const Vec3V r = V3Neg(*(const Vec3V*)&in[0]); memcpy(out, &r, sizeof(r)); } break;
  case 68: { const Vec3V r = V3Add(*(const Vec3V*)&in[0], *(const Vec3V*)&in[4]); memcpy(out, &r, sizeof(r)); } break;
  case 69: { const Vec3V r = V3Sub(*(const Vec3V*)&in[0], *(const Vec3V*)&in[4]); memcpy(out, &r, sizeof(r)); } break;
  case 70: { const Vec3V r = V3Scale(*(const Vec3V*)&in[0], *(const FloatV*)&in[4]); memcpy(out, &r, sizeof(r)); } break;
  case 71: { const Vec3V r = V3Mul(*(const Vec3V*)&in[0], *(const Vec3V*)&in[4]); memcpy(out, &r, sizeof(r)); } break;
  case 72: { const Vec3V r = V3ScaleInv(*(const Vec3V*)&in[0], *(const FloatV*)&in[4]); memcpy(out, &r, sizeof(r)); } break;
  case 73: { const Vec3V r = V3Div(*(const Vec3V*)&in[0], *(const Vec3V*)&in[4]); memcpy(out, &r, sizeof(r)); } break;
  case 74: { const Vec3V r = V3ScaleInvFast(*(const Vec3V*)&in[0], *(const FloatV*)&in[4]); memcpy(out, &r, sizeof(r)); } break;
  case 75: { const Vec3V r = V3DivFast(*(const Vec3V*)&in[0], *(const Vec3V*)&in[4]); memcpy(out, &r, sizeof(r)); } break;
  case 76: { const Vec3V r = V3Recip(*(const Vec3V*)&in[0]); memcpy(out, &r, sizeof(r)); } break;
  case 77: { const Vec3V r = V3RecipFast(*(const Vec3V*)&in[0]); memcpy(out, &r, sizeof(r)); } break;
  case 78: { const Vec3V r = V3Rsqrt(*(const Vec3V*)&in[0]); memcpy(out, &r, sizeof(r)); } break;
  case 79: { const Vec3V r = V3RsqrtFast(*(const Vec3V*)&in[0]); memcpy(out, &r, sizeof(r)); } break;
  case 80: { const Vec3V r = V3ScaleAdd(*(const Vec3V*)&in[0], *(const FloatV*)&in[4], *(const Vec3V*)&in[8]); memcpy(out, &r, sizeof(r)); } break;
  case 81: { const Vec3V r = V3NegScaleSub(*(const Vec3V*)&in[0], *(const FloatV*)&in[4], *(const Vec3V*)&in[8]); memcpy(out, &r, sizeof(r)); } break;
  case 82: { const Vec3V r = V3MulAdd(*(const Vec3V*)&in[0], *(const Vec3V*)&in[4], *(const Vec3V*)&in[8]); memcpy(out, &r, sizeof(r)); } break;
  case 83: { const Vec3V r = V3NegMulSub(*(const Vec3V*)&in[0], *(const Vec3V*)&in[4], *(const Vec3V*)&in[8]); memcpy(out, &r, sizeof(r)); } break;
  case 84: { const Vec3V r = V3Abs(*(const Vec3V*)&in[0]); memcpy(out, &r, sizeof(r)); } break;
  case 85: { const FloatV r0 = V3Dot(*(const Vec3V*)&in[0], *(const Vec3V*)&in[4]); const Vec4V r = r0; memcpy(out, &r, sizeof(r)); } break;
  case 86: { const Vec3V r = V3Cross(*(const Vec3V*)&in[0], *(const Vec3V*)&in[4]); memcpy(out, &r, sizeof(r)); } break;
  case 87: { const FloatV r0 = V3Length(*(const Vec3V*)&in[0]); const Vec4V r = r0; memcpy(out, &r, sizeof(r)); } break;
  case 88: { const FloatV r0 = V3LengthSq(*(const Vec3V*)&in[0]); const Vec4V r = r0; memcpy(out, &r, sizeof(r)); } break;
  case 89: { const Vec3V r = V3Normalize(*(const Vec3V*)&in[0]); memcpy(out, &r, sizeof(r)); } break;
  case 90: { const Vec3V r = V3NormalizeSafe(*(const Vec3V*)&in[0], *(const Vec3V*)&in[4]); memcpy(out, &r, sizeof(r)); } break;
  case 91: { const FloatV r0 = V3SumElems(*(const Vec3V*)&in[0]); const Vec4V r = r0; memcpy(out, &r, sizeof(r)); } break;
  case 92: { const Vec3V r = V3Sel(*(const BoolV*)&in[0], *(const Vec3V*)&in[4], *(const Vec3V*)&in[8]); memcpy(out, &r, sizeof(r)); } break;
  case 93: { const BoolV r = V3IsGrtr(*(const Vec3V*)&in[0], *(const Vec3V*)&in[4]); memcpy(out, &r, sizeof(r)); } break;
  case 94: { const BoolV r = V3IsGrtrOrEq(*(const Vec3V*)&in[0], *(const Vec3V*)&in[4]); memcpy(out, &r, sizeof(r)); } break;
  case 95: { const BoolV r = V3IsEq(*(const Vec3V*)&in[0], *(const Vec3V*)&in[4]); memcpy(out, &r, sizeof(r)); } break;
  case 96: { const Vec3V r = V3Max(*(const Vec3V*)&in[0], *(const Vec3V*)&in[4]); memcpy(out, &r, sizeof(r)); } break;
  case 97: { const Vec3V r = V3Min(*(const Vec3V*)&in[0], *(const Vec3V*)&in[4]); memcpy(out, &r, sizeof(r)); } break;
  case 98: { const FloatV r0 = V3ExtractMax(*(const Vec3V*)&in[0]); const Vec4V r = r0; memcpy(out, &r, sizeof(r)); } break;
  case 99: { const FloatV r0 = V3ExtractMin(*(const Vec3V*)&in[0]); const Vec4V r = r0; memcpy(out, &r, sizeof(r)); } break;
  case 100: { const Vec3V r = V3Clamp(*(const Vec3V*)&in[0], *(const Vec3V*)&in[4], *(const Vec3V*)&in[8]); memcpy(out, &r, sizeof(r)); } break;
  case 101: { const Vec3V r = V3Sign(*(const Vec3V*)&in[0]); memcpy(out, &r, sizeof(r)); } break;
  case 102: { const uint32_t r = V3AllGrtr(*(const Vec3V*)&in[0], *(const Vec3V*)&in[4]); memcpy(out, &r, 4); } break;
  case 103: { const uint32_t r = V3AllGrtrOrEq(*(const Vec3V*)&in[0], *(const Vec3V*)&in[4]); memcpy(out, &r, 4); } break;
  case 104: { const uint32_t r = V3AllEq(*(const Vec3V*)&in[0], *(const Vec3V*)&in[4]); memcpy(out, &r, 4); } break;
  case 105: { const uint32_t r = V3OutOfBounds(*(const Vec3V*)&in[0], *(const Vec3V*)&in[4], *(const Vec3V*)&in[8]); memcpy(out, &r, 4); } break;
  case 106: { const uint32_t r = V3InBounds(*(const Vec3V*)&in[0], *(const Vec3V*)&in[4], *(const Vec3V*)&in[8]); memcpy(out, &r, 4); } break;
  case 107: { const Vec3V r = V3Round(*(const Vec3V*)&in[0]); memcpy(out, &r, sizeof(r)); } break;
  case 108: { const Vec3V r = V3Sin(*(const Vec3V*)&in[0]); memcpy(out, &r, sizeof(r)); } break;
  case 109: { const Vec3V r = V3Cos(*(const Vec3V*)&in[0]); memcpy(out, &r, sizeof(r)); } break;
  case 110: { const Vec3V r = V3PermYZZ(*(const Vec3V*)&in[0]); memcpy(out, &r, sizeof(r)); } break;
  case 111: { const Vec3V r = V3PermXYX(*(const Vec3V*)&in[0]); memcpy(out, &r, sizeof(r)); } break;
  case 112: { const Vec3V r = V3PermYZX(*(const Vec3V*)&in[0]); memcpy(out, &r, sizeof(r)); } break;
  case 113: { const Vec3V r = V3PermZXY(*(const Vec3V*)&in[0]); memcpy(out, &r, sizeof(r)); } break;
  case 114: { const Vec3V r = V3PermZZY(*(const Vec3V*)&in[0]); memcpy(out, &r, sizeof(r)); } break;
  case 115: { const Vec3V r = V3PermYXX(*(const Vec3V*)&in[0]); memcpy(out, &r, sizeof(r)); } break;
  case 116: { const Vec3V r = V3Perm_Zero_1Z_0Y(*(const Vec3V*)&in[0], *(const Vec3V*)&in[4]); memcpy(out, &r, sizeof(r)); } break;
  case 117: { const Vec3V r = V3Perm_0Z_Zero_1X(*(const Vec3V*)&in[0], *(const Vec3V*)&in[4]); memcpy(out, &r, sizeof(r)); } break;
  case 118: { const Vec3V r = V3Perm_1Y_0X_Zero(*(const Vec3V*)&in[0], *(const Vec3V*)&in[4]); memcpy(out, &r, sizeof(r)); } break;
  case 119: { const Vec4V r = V4Splat(*(const FloatV*)&in[0]); memcpy(out, &r, sizeof(r)); } break;
  case 120: { const Vec4V r = V4Merge(*(const FloatV*)&in[0], *(const FloatV*)&in[4], *(const FloatV*)&in[8], *(const FloatV*)&in[12]); memcpy(out, &r, sizeof(r)); } break;
  case 121: { const Vec4V r = V4MergeW(*(const Vec4V*)&in[0], *(const Vec4V*)&in[4], *(const Vec4V*)&in[8], *(const Vec4V*)&in[12]); memcpy(out, &r, sizeof(r)); } break;
  case 122: { const Vec4V r = V4MergeZ(*(const Vec4V*)&in[0], *(const Vec4V*)&in[4], *(const Vec4V*)&in[8], *(const Vec4V*)&in[12]); memcpy(out, &r, sizeof(r)); } break;
  case 123: { const Vec4V r = V4MergeY(*(const Vec4V*)&in[0], *(const Vec4V*)&in[4], *(const Vec4V*)&in[8], *(const Vec4V*)&in[12]); memcpy(out, &r, sizeof(r)); } break;
  case 124: { const Vec4V r = V4MergeX(*(const Vec4V*)&in[0], *(const Vec4V*)&in[4], *(const Vec4V*)&in[8], *(const Vec4V*)&in[12]); memcpy(out, &r, sizeof(r)); } break;
  case 125: { const Vec4V r = V4UnpackXY(*(const Vec4V*)&in[0], *(const Vec4V*)&in[4]); memcpy(out, &r, sizeof(r)); } break;
  case 126: { const Vec4V r = V4UnpackZW(*(const Vec4V*)&in[0], *(const Vec4V*)&in[4]); memcpy(out, &r, sizeof(r)); } break;
  case 127: { const Vec4V r = V4UnitW(); memcpy(out, &r, sizeof(r)); } break;
  case 128: { const Vec4V r = V4UnitY(); memcpy(out, &r, sizeof(r)); } break;
  case 129: { const Vec4V r = V4UnitZ(); memcpy(out, &r, sizeof(r)); } break;
  case 130: { const FloatV r0 = V4GetX(*(const Vec4V*)&in[0]); const Vec4V r = r0; memcpy(out, &r, sizeof(r)); } break;
  case 131: { const FloatV r0 = V4GetY(*(const Vec4V*)&in[0]); const Vec4V r = r0; memcpy(out, &r, sizeof(r)); } break;
  case 132: { const FloatV r0 = V4GetZ(*(const Vec4V*)&in[0]); const Vec4V r = r0; memcpy(out, &r, sizeof(r)); } break;
  case 133: { const FloatV r0 = V4GetW(*(const Vec4V*)&in[0]); const Vec4V r = r0; memcpy(out, &r, sizeof(r)); } break;
  case 134: { const Vec4V r = V4SetX(*(const Vec4V*)&in[0], *(const FloatV*)&in[4]); memcpy(out, &r, sizeof(r)); } break;
  case 135: { const Vec4V r = V4SetY(*(const Vec4V*)&in[0], *(const FloatV*)&in[4]); memcpy(out, &r, sizeof(r)); } break;
  case 136: { const Vec4V r = V4SetZ(*(const Vec4V*)&in[0], *(const FloatV*)&in[4]); memcpy(out, &r, sizeof(r)); } break;
  case 137: { const Vec4V r = V4SetW(*(const Vec4V*)&in[0], *(const FloatV*)&in[4]); memcpy(out, &r, sizeof(r)); } break;
  case 138: { const Vec4V r = V4ClearW(*(const Vec4V*)&in[0]); memcpy(out, &r, sizeof(r)); } break;
  case 139: { const float r = V4ReadX(*(const Vec4V*)&in[0]); memcpy(out, &r, 4); } break;
  case 140: { const float r = V4ReadY(*(const Vec4V*)&in[0]); memcpy(out, &r, 4); } break;
  case 141: { const float r = V4ReadZ(*(const Vec4V*)&in[0]); memcpy(out, &r, 4); } break;
  case 142: { const float r = V4ReadW(*(const Vec4V*)&in[0]); memcpy(out, &r, 4); } break;
  case 143: { const Vec4V r = V4Zero(); memcpy(out, &r, sizeof(r)); } break;
  case 144: { const Vec4V r = V4One(); memcpy(out, &r, sizeof(r)); } break;
  case 145: { const Vec4V r = V4Eps(); memcpy(out, &r, sizeof(r)); } break;
  case 146: { const Vec4V r = V4Neg(*(const Vec4V*)&in[0]); memcpy(out, &r, sizeof(r)); } break;
  case 147: { const Vec4V r = V4Add(*(const Vec4V*)&in[0], *(const Vec4V*)&in[4]); memcpy(out, &r, sizeof(r)); } break;
  case 148: { const Vec4V r = V4Sub(*(const Vec4V*)&in[0], *(const Vec4V*)&in[4]); memcpy(out, &r, sizeof(r)); } break;
  case 149: { const Vec4V r = V4Scale(*(const Vec4V*)&in[0], *(const FloatV*)&in[4]); memcpy(out, &r, sizeof(r)); } break;
  case 150: { const Vec4V r = V4Mul(*(const Vec4V*)&in[0], *(const Vec4V*)&in[4]); memcpy(out, &r, sizeof(r)); } break;
  case 151: { const Vec4V r = V4ScaleInv(*(const Vec4V*)&in[0], *(const FloatV*)&in[4]); memcpy(out, &r, sizeof(r)); } break;
  case 152: { const Vec4V r = V4Div(*(const Vec4V*)&in[0], *(const Vec4V*)&in[4]); memcpy(out, &r, sizeof(r)); } break;
  case 153: { const Vec4V r = V4ScaleInvFast(*(const Vec4V*)&in[0], *(const FloatV*)&in[4]); memcpy(out, &r, sizeof(r)); } break;
  case 154: { const Vec4V r = V4DivFast(*(const Vec4V*)&in[0], *(const Vec4V*)&in[4]); memcpy(out, &r, sizeof(r)); } break;
  case 155: { const Vec4V r = V4Recip(*(const Vec4V*)&in[0]); memcpy(out, &r, sizeof(r)); } break;
  case 156: { const Vec4V r = V4RecipFast(*(const Vec4V*)&in[0]); memcpy(out, &r, sizeof(r)); } break;
  case 157: { const Vec4V r = V4Rsqrt(*(const Vec4V*)&in[0]); memcpy(out, &r, sizeof(r)); } break;
  case 158: { const Vec4V r = V4RsqrtFast(*(const Vec4V*)&in[0]); memcpy(out, &r, sizeof(r)); } break;
  case 159: { const Vec4V r = V4ScaleAdd(*(const Vec4V*)&in[0], *(const FloatV*)&in[4], *(const Vec4V*)&in[8]); memcpy(out, &r, sizeof(r)); } break;
  case 160: { const Vec4V r = V4NegScaleSub(*(const Vec4V*)&in[0], *(const FloatV*)&in[4], *(const Vec4V*)&in[8]); memcpy(out, &r, sizeof(r)); } break;
  case 161: { const Vec4V r = V4MulAdd(*(const Vec4V*)&in[0], *(const Vec4V*)&in[4], *(const Vec4V*)&in[8]); memcpy(out, &r, sizeof(r)); } break;
  case 162: { const Vec4V r = V4NegMulSub(*(const Vec4V*)&in[0], *(const Vec4V*)&in[4], *(const Vec4V*)&in[8]); memcpy(out, &r, sizeof(r)); } break;
  case 163: { const Vec4V r = V4Abs(*(const Vec4V*)&in[0]); memcpy(out, &r, sizeof(r)); } break;
  case 164: { const Vec4V r = V4Andc(*(const Vec4V*)&in[0], *(const VecU32V*)&in[4]); memcpy(out, &r, sizeof(r)); } break;
  case 165: { const FloatV r0 = V4Dot(*(const Vec4V*)&in[0], *(const Vec4V*)&in[4]); const Vec4V r = r0; memcpy(out, &r, sizeof(r)); } break;
  case 166: { const FloatV r0 = V4Dot3(*(const Vec4V*)&in[0], *(const Vec4V*)&in[4]); const Vec4V r = r0; memcpy(out, &r, sizeof(r)); } break;
  case 167: { const Vec4V r = V4Cross(*(const Vec4V*)&in[0], *(const Vec4V*)&in[4]); memcpy(out, &r, sizeof(r)); } break;
  case 168: { const FloatV r0 = V4Length(*(const Vec4V*)&in[0]); const Vec4V r = r0; memcpy(out, &r, sizeof(r)); } break;
  case 169: { const FloatV r0 = V4LengthSq(*(const Vec4V*)&in[0]); const Vec4V r = r0; memcpy(out, &r, sizeof(r)); } break;
  case 170: { const Vec4V r = V4Normalize(*(const Vec4V*)&in[0]); memcpy(out, &r, sizeof(r)); } break;
  case 171: { const Vec4V r = V4NormalizeSafe(*(const Vec4V*)&in[0], *(const Vec4V*)&in[4]); memcpy(out, &r, sizeof(r)); } break;
  case 172: { const Vec4V r = V4NormalizeFast(*(const Vec4V*)&in[0]); memcpy(out, &r, sizeof(r)); } break;
  case 173: { const Vec4V r = V4Sel(*(const BoolV*)&in[0], *(const Vec4V*)&in[4], *(const Vec4V*)&in[8]); memcpy(out, &r, sizeof(r)); } break;
  case 174: { const BoolV r = V4IsGrtr(*(const Vec4V*)&in[0], *(const Vec4V*)&in[4]); memcpy(out, &r, sizeof(r)); } break;
  case 175: { const BoolV r = V4IsGrtrOrEq(*(const Vec4V*)&in[0], *(const Vec4V*)&in[4]); memcpy(out, &r, sizeof(r)); } break;
  case 176: { const BoolV r = V4IsEq(*(const Vec4V*)&in[0], *(const Vec4V*)&in[4]); memcpy(out, &r, sizeof(r)); } break;
  case 177: { const Vec4V r = V4Max(*(const Vec4V*)&in[0], *(const Vec4V*)&in[4]); memcpy(out, &r, sizeof(r)); } break;
  case 178: { const Vec4V r = V4Min(*(const Vec4V*)&in[0], *(const Vec4V*)&in[4]); memcpy(out, &r, sizeof(r)); } break;
  case 179: { const FloatV r0 = V4ExtractMax(*(const Vec4V*)&in[0]); const Vec4V r = r0; memcpy(out, &r, sizeof(r)); } break;
  case 180: { const FloatV r0 = V4ExtractMin(*(const Vec4V*)&in[0]); const Vec4V r = r0; memcpy(out, &r, sizeof(r)); } break;
  case 181: { const Vec4V r = V4Clamp(*(const Vec4V*)&in[0], *(const Vec4V*)&in[4], *(const Vec4V*)&in[8]); memcpy(out, &r, sizeof(r)); } break;
  case 182: { const uint32_t r = V4AllGrtr(*(const Vec4V*)&in[0], *(const Vec4V*)&in[4]); memcpy(out, &r, 4); } break;
  case 183: { const uint32_t r = V4AllGrtrOrEq(*(const Vec4V*)&in[0], *(const Vec4V*)&in[4]); memcpy(out, &r, 4); } break;
  case 184: { const uint32_t r = V4AllGrtrOrEq3(*(const Vec4V*)&in[0], *(const Vec4V*)&in[4]); memcpy(out, &r, 4); } break;
  case 185: { const uint32_t r = V4AllEq(*(const Vec4V*)&in[0], *(const Vec4V*)&in[4]); memcpy(out, &r, 4); } break;
  case 186: { const uint32_t r = V4AnyGrtr3(*(const Vec4V*)&in[0], *(const Vec4V*)&in[4]); memcpy(out, &r, 4); } break;
  case 187: { const Vec4V r = V4Round(*(const Vec4V*)&in[0]); memcpy(out, &r, sizeof(r)); } break;
  case 188: { const Vec4V r = V4Sin(*(const Vec4V*)&in[0]); memcpy(out, &r, sizeof(r)); } break;
  case 189: { const Vec4V r = V4Cos(*(const Vec4V*)&in[0]); memcpy(out, &r, sizeof(r)); } break;
  case 190: { const Vec4V r = V4PermYXWZ(*(const Vec4V*)&in[0]); memcpy(out, &r, sizeof(r)); } break;
  case 191: { const Vec4V r = V4PermXZXZ(*(const Vec4V*)&in[0]); memcpy(out, &r, sizeof(r)); } break;
  case 192: { const Vec4V r = V4PermYWYW(*(const Vec4V*)&in[0]); memcpy(out, &r, sizeof(r)); } break;
  case 193: { const Vec4V r = V4PermYZXW(*(const Vec4V*)&in[0]); memcpy(out, &r, sizeof(r)); } break;
  case 194: { const Vec4V r = V4PermZWXY(*(const Vec4V*)&in[0]); memcpy(out, &r, sizeof(r)); } break;
  case 195: { const QuatV r = QuatV_From_RotationAxisAngle(*(const Vec3V*)&in[0], *(const FloatV*)&in[4]); memcpy(out, &r, sizeof(r)); } break;
  case 196: { const QuatV r = QuatNormalize(*(const QuatV*)&in[0]); memcpy(out, &r, sizeof(r)); } break;
  case 197: { const FloatV r0 = QuatLength(*(const QuatV*)&in[0]); const Vec4V r = r0; memcpy(out, &r, sizeof(r)); } break;
  case 198: { const FloatV r0 = QuatLengthSq(*(const QuatV*)&in[0]); const Vec4V r = r0; memcpy(out, &r, sizeof(r)); } break;
  case 199: { const FloatV r0 = QuatDot(*(const QuatV*)&in[0], *(const QuatV*)&in[4]); const Vec4V r = r0; memcpy(out, &r, sizeof(r)); } break;
  case 200: { const QuatV r = QuatConjugate(*(const QuatV*)&in[0]); memcpy(out, &r, sizeof(r)); } break;
  case 201: { const Vec3V r = QuatGetImaginaryPart(*(const QuatV*)&in[0]); memcpy(out, &r, sizeof(r)); } break;
  case 202: { const Mat33V r = QuatGetMat33V(*(const QuatV*)&in[0]); memcpy(out, &r, sizeof(r)); } break;
  case 203: { const QuatV r = Mat33GetQuatV(*(const Mat33V*)&in[0]); memcpy(out, &r, sizeof(r)); } break;
  case 204: { const Vec3V r = QuatGetBasisVector0(*(const QuatV*)&in[0]); memcpy(out, &r, sizeof(r)); } break;
  case 205: { const Vec3V r = QuatGetBasisVector1(*(const QuatV*)&in[0]); memcpy(out, &r, sizeof(r)); } break;
  case 206: { const Vec3V r = QuatGetBasisVector2(*(const QuatV*)&in[0]); memcpy(out, &r, sizeof(r)); } break;
  case 207: { const Vec3V r = QuatRotate(*(const QuatV*)&in[0], *(const Vec3V*)&in[4]); memcpy(out, &r, sizeof(r)); } break;
  case 208: { const Vec3V r = QuatRotateInv(*(const QuatV*)&in[0], *(const Vec3V*)&in[4]); memcpy(out, &r, sizeof(r)); } break;
  case 209: { const QuatV r = QuatMul(*(const QuatV*)&in[0], *(const QuatV*)&in[4]); memcpy(out, &r, sizeof(r)); } break;
  case 210: { const QuatV r = QuatAdd(*(const QuatV*)&in[0], *(const QuatV*)&in[4]); memcpy(out, &r, sizeof(r)); } break;
  case 211: { const QuatV r = QuatNeg(*(const QuatV*)&in[0]); memcpy(out, &r, sizeof(r)); } break;
  case 212: { const QuatV r = QuatSub(*(const QuatV*)&in[0], *(const QuatV*)&in[4]); memcpy(out, &r, sizeof(r)); } break;
  case 213: { const QuatV r = QuatScale(*(const QuatV*)&in[0], *(const FloatV*)&in[4]); memcpy(out, &r, sizeof(r)); } break;
  case 214: { const QuatV r = QuatMerge(*(const FloatV*)&in[0], *(const FloatV*)&in[4], *(const FloatV*)&in[8], *(const FloatV*)&in[12]); memcpy(out, &r, sizeof(r)); } break;
  case 215: { const QuatV r = QuatIdentity(); memcpy(out, &r, sizeof(r)); } break;
  case 216: { const float r = isFiniteQuatV(*(const QuatV*)&in[0]) ? 1.0f : 0.0f; memcpy(out, &r, 4); } break;
  case 217: { const float r = isValidQuatV(*(const QuatV*)&in[0]) ? 1.0f : 0.0f; memcpy(out, &r, 4); } break;
  case 218: { const float r = isSaneQuatV(*(const QuatV*)&in[0]) ? 1.0f : 0.0f; memcpy(out, &r, 4); } break;
  case 219: { const BoolV r = BFFFF(); memcpy(out, &r, sizeof(r)); } break;
  case 220: { const BoolV r = BFFFT(); memcpy(out, &r, sizeof(r)); } break;
  case 221: { const BoolV r = BFFTF(); memcpy(out, &r, sizeof(r)); } break;
  case 222: { const BoolV r = BFFTT(); memcpy(out, &r, sizeof(r)); } break;
  case 223: { const BoolV r = BFTFF(); memcpy(out, &r, sizeof(r)); } break;
  case 224: { const BoolV r = BFTFT(); memcpy(out, &r, sizeof(r)); } break;
  case 225: { const BoolV r = BFTTF(); memcpy(out, &r, sizeof(r)); } break;
  case 226: { const BoolV r = BFTTT(); memcpy(out, &r, sizeof(r)); } break;
  case 227: { const BoolV r = BTFFF(); memcpy(out, &r, sizeof(r)); } break;
  case 228: { const BoolV r = BTFFT(); memcpy(out, &r, sizeof(r)); } break;
  case 229: { const BoolV r = BTFTF(); memcpy(out, &r, sizeof(r)); } break;
  case 230: { const BoolV r = BTFTT(); memcpy(out, &r, sizeof(r)); } break;
  case 231: { const BoolV r = BTTFF(); memcpy(out, &r, sizeof(r)); } break;
  case 232: { const BoolV r = BTTFT(); memcpy(out, &r, sizeof(r)); } break;
  case 233: { const BoolV r = BTTTF(); memcpy(out, &r, sizeof(r)); } break;
  case 234: { const BoolV r = BTTTT(); memcpy(out, &r, sizeof(r)); } break;
  case 235: { const BoolV r = BWMask(); memcpy(out, &r, sizeof(r)); } break;
  case 236: { const BoolV r = BXMask(); memcpy(out, &r, sizeof(r)); } break;
  case 237: { const BoolV r = BYMask(); memcpy(out, &r, sizeof(r)); } break;
  case 238: { const BoolV r = BZMask(); memcpy(out, &r, sizeof(r)); } break;
  case 239: { const BoolV r = BGetX(*(const BoolV*)&in[0]); memcpy(out, &r, sizeof(r)); } break;
  case 240: { const BoolV r = BGetY(*(const BoolV*)&in[0]); memcpy(out, &r, sizeof(r)); } break;
  case 241: { const BoolV r = BGetZ(*(const BoolV*)&in[0]); memcpy(out, &r, sizeof(r)); } break;
  case 242: { const BoolV r = BGetW(*(const BoolV*)&in[0]); memcpy(out, &r, sizeof(r)); } break;
  case 243: { const BoolV r = BAnd(*(const BoolV*)&in[0], *(const BoolV*)&in[4]); memcpy(out, &r, sizeof(r)); } break;
  case 244: { const BoolV r = BOr(*(const BoolV*)&in[0], *(const BoolV*)&in[4]); memcpy(out, &r, sizeof(r)); } break;
  case 245: { const BoolV r = BNot(*(const BoolV*)&in[0]); memcpy(out, &r, sizeof(r)); } break;
  case 246: { const BoolV r = BAllTrue4(*(const BoolV*)&in[0]); memcpy(out, &r, sizeof(r)); } break;
  case 247: { const BoolV r = BAnyTrue4(*(const BoolV*)&in[0]); memcpy(out, &r, sizeof(r)); } break;
  case 248: { const BoolV r = BAllTrue3(*(const BoolV*)&in[0]); memcpy(out, &r, sizeof(r)); } break;
  case 249: { const BoolV r = BAnyTrue3(*(const BoolV*)&in[0]); memcpy(out, &r, sizeof(r)); } break;
  case 250: { const uint32_t r = BAllEq(*(const BoolV*)&in[0], *(const BoolV*)&in[4]); memcpy(out, &r, 4); } break;
  case 251: { const uint32_t r = BAllEqTTTT(*(const BoolV*)&in[0]); memcpy(out, &r, 4); } break;
  case 252: { const uint32_t r = BAllEqFFFF(*(const BoolV*)&in[0]); memcpy(out, &r, 4); } break;
  case 253: { const VecI32V r = VecI32V_Zero(); memcpy(out, &r, sizeof(r)); } break;
  case 254: { const VecI32V r = VecI32V_One(); memcpy(out, &r, sizeof(r)); } break;
  case 255: { const VecI32V r = VecI32V_Two(); memcpy(out, &r, sizeof(r)); } break;
  case 256: { const VecI32V r = VecI32V_MinusOne(); memcpy(out, &r, sizeof(r)); } break;
  case 257: { const VecI32V r = VecI32V_Add(*(const VecI32V*)&in[0], *(const VecI32V*)&in[4]); memcpy(out, &r, sizeof(r)); } break;
  case 258: { const VecI32V r = VecI32V_Or(*(const VecI32V*)&in[0], *(const VecI32V*)&in[4]); memcpy(out, &r, sizeof(r)); } break;
  case 259: { const VecI32V r = VecI32V_GetX(*(const VecI32V*)&in[0]); memcpy(out, &r, sizeof(r)); } break;
  case 260: { const VecI32V r = VecI32V_GetY(*(const VecI32V*)&in[0]); memcpy(out, &r, sizeof(r)); } break;
  case 261: { const VecI32V r = VecI32V_GetZ(*(const VecI32V*)&in[0]); memcpy(out, &r, sizeof(r)); } break;
  case 262: { const VecI32V r = VecI32V_GetW(*(const VecI32V*)&in[0]); memcpy(out, &r, sizeof(r)); } break;
  case 263: { const VecI32V r = VecI32V_Sub(*(const VecI32V*)&in[0], *(const VecI32V*)&in[4]); memcpy(out, &r, sizeof(r)); } break;
  case 264: { const BoolV r = VecI32V_IsGrtr(*(const VecI32V*)&in[0], *(const VecI32V*)&in[4]); memcpy(out, &r, sizeof(r)); } break;
  case 265: { const BoolV r = VecI32V_IsEq(*(const VecI32V*)&in[0], *(const VecI32V*)&in[4]); memcpy(out, &r, sizeof(r)); } break;
  case 266: { const VecU32V r = U4Zero(); memcpy(out, &r, sizeof(r)); } break;
  case 267: { const VecU32V r = U4One(); memcpy(out, &r, sizeof(r)); } break;
  case 268: { const VecU32V r = U4Two(); memcpy(out, &r, sizeof(r)); } break;
  case 269: { const BoolV r = V4IsEqU32(*(const VecU32V*)&in[0], *(const VecU32V*)&in[4]); memcpy(out, &r, sizeof(r)); } break;
  case 270: { const VecU32V r = V4U32or(*(const VecU32V*)&in[0], *(const VecU32V*)&in[4]); memcpy(out, &r, sizeof(r)); } break;
  case 271: { const VecU32V r = V4U32xor(*(const VecU32V*)&in[0], *(const VecU32V*)&in[4]); memcpy(out, &r, sizeof(r)); } break;
  case 272: { const VecU32V r = V4U32and(*(const VecU32V*)&in[0], *(const VecU32V*)&in[4]); memcpy(out, &r, sizeof(r)); } break;
  case 273: { const VecU32V r = V4U32Andc(*(const VecU32V*)&in[0], *(const VecU32V*)&in[4]); memcpy(out, &r, sizeof(r)); } break;
  case 274: { const VecU32V r = V4IsGrtrV32u(*(const Vec4V*)&in[0], *(const Vec4V*)&in[4]); memcpy(out, &r, sizeof(r)); } break;
  case 275: { const Vec3V r = M33MulV3(*(const Mat33V*)&in[0], *(const Vec3V*)&in[16]); memcpy(out, &r, sizeof(r)); } break;
  case 276: { const Vec3V r = M33MulV3AddV3(*(const Mat33V*)&in[0], *(const Vec3V*)&in[16], *(const Vec3V*)&in[20]); memcpy(out, &r, sizeof(r)); } break;
  case 277: { const Vec3V r = M33TrnspsMulV3(*(const Mat33V*)&in[0], *(const Vec3V*)&in[16]); memcpy(out, &r, sizeof(r)); } break;
  case 278: { const Mat33V r = M33MulM33(*(const Mat33V*)&in[0], *(const Mat33V*)&in[16]); memcpy(out, &r, sizeof(r)); } break;
  case 279: { const Mat33V r = M33Add(*(const Mat33V*)&in[0], *(const Mat33V*)&in[16]); memcpy(out, &r, sizeof(r)); } break;
  case 280: { const Mat33V r = M33Sub(*(const Mat33V*)&in[0], *(const Mat33V*)&in[16]); memcpy(out, &r, sizeof(r)); } break;
  case 281: { const Mat33V r = M33Neg(*(const Mat33V*)&in[0]); memcpy(out, &r, sizeof(r)); } break;
  case 282: { const Mat33V r = M33Abs(*(const Mat33V*)&in[0]); memcpy(out, &r, sizeof(r)); } break;
  case 283: { const Mat33V r = M33Inverse(*(const Mat33V*)&in[0]); memcpy(out, &r, sizeof(r)); } break;
  case 284: { const Mat33V r = M33Trnsps(*(const Mat33V*)&in[0]); memcpy(out, &r, sizeof(r)); } break;
  case 285: { const Mat33V r = M33Identity(); memcpy(out, &r, sizeof(r)); } break;
  }
}
__global__ void aos_kernel(int fid, const float* in, float* out, int n) {
  const int i = blockIdx.x * blockDim.x + threadIdx.x;
  if (i < n) aos_call(fid, in + 64 * i, out + 16 * i);
}
extern "C" int gpu_run(int fid, const float* in, float* out, int n) {
  float *din = nullptr, *dout = nullptr;
  if (cudaMalloc(&din, sizeof(float) * 64 * n) || cudaMalloc(&dout, sizeof(float) * 16 * n)) return 1;
  cudaMemcpy(din, in, sizeof(float) * 64 * n, cudaMemcpyHostToDevice);
  cudaMemset(dout, 0, sizeof(float) * 16 * n);
  aos_kernel<<<(n + 127) / 128, 128>>>(fid, din, dout, n);
  cudaError_t e = cudaMemcpy(out, dout, sizeof(float) * 16 * n, cudaMemcpyDeviceToHost);
  cudaFree(din); cudaFree(dout);
  return e != cudaSuccess;
}
