// 생성물 (gen_aos_test.py): 진짜 PhysX aos (SSE 하드웨어)
#include "foundation/PxVecMath.h"
#include "foundation/PxVecTransform.h"
#include <cstring>
#include <cstdint>
using namespace physx::aos;
extern "C" void px_QuatVLoadXYZW(const float* in, float* out) { const QuatV r = QuatVLoadXYZW(in[0], in[4], in[8], in[12]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_Vec3V_From_Vec4V(const float* in, float* out) { const Vec3V r = Vec3V_From_Vec4V(*(const Vec4V*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_Vec3V_From_Vec4V_WUndefined(const float* in, float* out) { const Vec3V r = Vec3V_From_Vec4V_WUndefined(*(const Vec4V*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_Vec4V_From_Vec3V(const float* in, float* out) { const Vec4V r = Vec4V_From_Vec3V(*(const Vec3V*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_Vec4V_From_VecU32V(const float* in, float* out) { const Vec4V r = Vec4V_From_VecU32V(*(const VecU32V*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_Vec4V_From_VecI32V(const float* in, float* out) { const Vec4V r = Vec4V_From_VecI32V(*(const VecI32V*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_VecU32V_From_BoolV(const float* in, float* out) { const VecU32V r = VecU32V_From_BoolV(*(const BoolV*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_VecI32V_From_Vec4V(const float* in, float* out) { const VecI32V r = VecI32V_From_Vec4V(*(const Vec4V*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_isFiniteFloatV(const float* in, float* out) { const float r = isFiniteFloatV(*(const FloatV*)&in[0]) ? 1.0f : 0.0f; memcpy(out, &r, 4); }
extern "C" void px_isFiniteVec3V(const float* in, float* out) { const float r = isFiniteVec3V(*(const Vec3V*)&in[0]) ? 1.0f : 0.0f; memcpy(out, &r, 4); }
extern "C" void px_isFiniteVec4V(const float* in, float* out) { const float r = isFiniteVec4V(*(const Vec4V*)&in[0]) ? 1.0f : 0.0f; memcpy(out, &r, 4); }
extern "C" void px_isValidVec3V(const float* in, float* out) { const float r = isValidVec3V(*(const Vec3V*)&in[0]) ? 1.0f : 0.0f; memcpy(out, &r, 4); }
extern "C" void px_getInvalidVec3V(const float* in, float* out) { const Vec3V r = getInvalidVec3V(); memcpy(out, &r, sizeof(r)); }
extern "C" void px_allElementsEqualFloatV(const float* in, float* out) { const float r = allElementsEqualFloatV(*(const FloatV*)&in[0], *(const FloatV*)&in[4]) ? 1.0f : 0.0f; memcpy(out, &r, 4); }
extern "C" void px_allElementsEqualVec3V(const float* in, float* out) { const float r = allElementsEqualVec3V(*(const Vec3V*)&in[0], *(const Vec3V*)&in[4]) ? 1.0f : 0.0f; memcpy(out, &r, 4); }
extern "C" void px_allElementsEqualVec4V(const float* in, float* out) { const float r = allElementsEqualVec4V(*(const Vec4V*)&in[0], *(const Vec4V*)&in[4]) ? 1.0f : 0.0f; memcpy(out, &r, 4); }
extern "C" void px_allElementsEqualBoolV(const float* in, float* out) { const float r = allElementsEqualBoolV(*(const BoolV*)&in[0], *(const BoolV*)&in[4]) ? 1.0f : 0.0f; memcpy(out, &r, 4); }
extern "C" void px_allElementsEqualVecU32V(const float* in, float* out) { const float r = allElementsEqualVecU32V(*(const VecU32V*)&in[0], *(const VecU32V*)&in[4]) ? 1.0f : 0.0f; memcpy(out, &r, 4); }
extern "C" void px_allElementsEqualVecI32V(const float* in, float* out) { const float r = allElementsEqualVecI32V(*(const VecI32V*)&in[0], *(const VecI32V*)&in[4]) ? 1.0f : 0.0f; memcpy(out, &r, 4); }
extern "C" void px_allElementsNearEqualFloatV(const float* in, float* out) { const float r = allElementsNearEqualFloatV(*(const FloatV*)&in[0], *(const FloatV*)&in[4]) ? 1.0f : 0.0f; memcpy(out, &r, 4); }
extern "C" void px_allElementsNearEqualVec3V(const float* in, float* out) { const float r = allElementsNearEqualVec3V(*(const Vec3V*)&in[0], *(const Vec3V*)&in[4]) ? 1.0f : 0.0f; memcpy(out, &r, 4); }
extern "C" void px_allElementsNearEqualVec4V(const float* in, float* out) { const float r = allElementsNearEqualVec4V(*(const Vec4V*)&in[0], *(const Vec4V*)&in[4]) ? 1.0f : 0.0f; memcpy(out, &r, 4); }
extern "C" void px_FZero(const float* in, float* out) { const FloatV r = FZero(); memcpy(out, &r, sizeof(r)); }
extern "C" void px_FOne(const float* in, float* out) { const FloatV r = FOne(); memcpy(out, &r, sizeof(r)); }
extern "C" void px_FHalf(const float* in, float* out) { const FloatV r = FHalf(); memcpy(out, &r, sizeof(r)); }
extern "C" void px_FEps(const float* in, float* out) { const FloatV r = FEps(); memcpy(out, &r, sizeof(r)); }
extern "C" void px_FMax(const float* in, float* out) { const FloatV r = FMax(); memcpy(out, &r, sizeof(r)); }
extern "C" void px_FNegMax(const float* in, float* out) { const FloatV r = FNegMax(); memcpy(out, &r, sizeof(r)); }
extern "C" void px_FEps6(const float* in, float* out) { const FloatV r = FEps6(); memcpy(out, &r, sizeof(r)); }
extern "C" void px_FNeg(const float* in, float* out) { const FloatV r = FNeg(*(const FloatV*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_FAdd(const float* in, float* out) { const FloatV r = FAdd(*(const FloatV*)&in[0], *(const FloatV*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_FSub(const float* in, float* out) { const FloatV r = FSub(*(const FloatV*)&in[0], *(const FloatV*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_FMul(const float* in, float* out) { const FloatV r = FMul(*(const FloatV*)&in[0], *(const FloatV*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_FDiv(const float* in, float* out) { const FloatV r = FDiv(*(const FloatV*)&in[0], *(const FloatV*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_FDivFast(const float* in, float* out) { const FloatV r = FDivFast(*(const FloatV*)&in[0], *(const FloatV*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_FRecip(const float* in, float* out) { const FloatV r = FRecip(*(const FloatV*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_FRecipFast(const float* in, float* out) { const FloatV r = FRecipFast(*(const FloatV*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_FRsqrt(const float* in, float* out) { const FloatV r = FRsqrt(*(const FloatV*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_FRsqrtFast(const float* in, float* out) { const FloatV r = FRsqrtFast(*(const FloatV*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_FSqrt(const float* in, float* out) { const FloatV r = FSqrt(*(const FloatV*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_FScaleAdd(const float* in, float* out) { const FloatV r = FScaleAdd(*(const FloatV*)&in[0], *(const FloatV*)&in[4], *(const FloatV*)&in[8]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_FNegScaleSub(const float* in, float* out) { const FloatV r = FNegScaleSub(*(const FloatV*)&in[0], *(const FloatV*)&in[4], *(const FloatV*)&in[8]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_FAbs(const float* in, float* out) { const FloatV r = FAbs(*(const FloatV*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_FSel(const float* in, float* out) { const FloatV r = FSel(*(const BoolV*)&in[0], *(const FloatV*)&in[4], *(const FloatV*)&in[8]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_FIsGrtr(const float* in, float* out) { const BoolV r = FIsGrtr(*(const FloatV*)&in[0], *(const FloatV*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_FIsGrtrOrEq(const float* in, float* out) { const BoolV r = FIsGrtrOrEq(*(const FloatV*)&in[0], *(const FloatV*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_FIsEq(const float* in, float* out) { const BoolV r = FIsEq(*(const FloatV*)&in[0], *(const FloatV*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_FMin(const float* in, float* out) { const FloatV r = FMin(*(const FloatV*)&in[0], *(const FloatV*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_FClamp(const float* in, float* out) { const FloatV r = FClamp(*(const FloatV*)&in[0], *(const FloatV*)&in[4], *(const FloatV*)&in[8]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_FAllGrtr(const float* in, float* out) { const uint32_t r = FAllGrtr(*(const FloatV*)&in[0], *(const FloatV*)&in[4]); memcpy(out, &r, 4); }
extern "C" void px_FAllGrtrOrEq(const float* in, float* out) { const uint32_t r = FAllGrtrOrEq(*(const FloatV*)&in[0], *(const FloatV*)&in[4]); memcpy(out, &r, 4); }
extern "C" void px_FAllEq(const float* in, float* out) { const uint32_t r = FAllEq(*(const FloatV*)&in[0], *(const FloatV*)&in[4]); memcpy(out, &r, 4); }
extern "C" void px_FOutOfBounds(const float* in, float* out) { const uint32_t r = FOutOfBounds(*(const FloatV*)&in[0], *(const FloatV*)&in[4], *(const FloatV*)&in[8]); memcpy(out, &r, 4); }
extern "C" void px_FInBounds(const float* in, float* out) { const uint32_t r = FInBounds(*(const FloatV*)&in[0], *(const FloatV*)&in[4], *(const FloatV*)&in[8]); memcpy(out, &r, 4); }
extern "C" void px_FRound(const float* in, float* out) { const FloatV r = FRound(*(const FloatV*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_FSin(const float* in, float* out) { const FloatV r = FSin(*(const FloatV*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_FCos(const float* in, float* out) { const FloatV r = FCos(*(const FloatV*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V3Splat(const float* in, float* out) { const Vec3V r = V3Splat(*(const FloatV*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V3Merge(const float* in, float* out) { const Vec3V r = V3Merge(*(const FloatV*)&in[0], *(const FloatV*)&in[4], *(const FloatV*)&in[8]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V3UnitX(const float* in, float* out) { const Vec3V r = V3UnitX(); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V3UnitY(const float* in, float* out) { const Vec3V r = V3UnitY(); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V3UnitZ(const float* in, float* out) { const Vec3V r = V3UnitZ(); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V3GetX(const float* in, float* out) { const FloatV r = V3GetX(*(const Vec3V*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V3GetY(const float* in, float* out) { const FloatV r = V3GetY(*(const Vec3V*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V3GetZ(const float* in, float* out) { const FloatV r = V3GetZ(*(const Vec3V*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V3SetX(const float* in, float* out) { const Vec3V r = V3SetX(*(const Vec3V*)&in[0], *(const FloatV*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V3SetY(const float* in, float* out) { const Vec3V r = V3SetY(*(const Vec3V*)&in[0], *(const FloatV*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V3SetZ(const float* in, float* out) { const Vec3V r = V3SetZ(*(const Vec3V*)&in[0], *(const FloatV*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V3ReadX(const float* in, float* out) { const float r = V3ReadX(*(const Vec3V*)&in[0]); memcpy(out, &r, 4); }
extern "C" void px_V3ReadY(const float* in, float* out) { const float r = V3ReadY(*(const Vec3V*)&in[0]); memcpy(out, &r, 4); }
extern "C" void px_V3ReadZ(const float* in, float* out) { const float r = V3ReadZ(*(const Vec3V*)&in[0]); memcpy(out, &r, 4); }
extern "C" void px_V3ColX(const float* in, float* out) { const Vec3V r = V3ColX(*(const Vec3V*)&in[0], *(const Vec3V*)&in[4], *(const Vec3V*)&in[8]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V3ColY(const float* in, float* out) { const Vec3V r = V3ColY(*(const Vec3V*)&in[0], *(const Vec3V*)&in[4], *(const Vec3V*)&in[8]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V3ColZ(const float* in, float* out) { const Vec3V r = V3ColZ(*(const Vec3V*)&in[0], *(const Vec3V*)&in[4], *(const Vec3V*)&in[8]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V3Zero(const float* in, float* out) { const Vec3V r = V3Zero(); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V3One(const float* in, float* out) { const Vec3V r = V3One(); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V3Eps(const float* in, float* out) { const Vec3V r = V3Eps(); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V3Neg(const float* in, float* out) { const Vec3V r = V3Neg(*(const Vec3V*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V3Add(const float* in, float* out) { const Vec3V r = V3Add(*(const Vec3V*)&in[0], *(const Vec3V*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V3Sub(const float* in, float* out) { const Vec3V r = V3Sub(*(const Vec3V*)&in[0], *(const Vec3V*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V3Scale(const float* in, float* out) { const Vec3V r = V3Scale(*(const Vec3V*)&in[0], *(const FloatV*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V3Mul(const float* in, float* out) { const Vec3V r = V3Mul(*(const Vec3V*)&in[0], *(const Vec3V*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V3ScaleInv(const float* in, float* out) { const Vec3V r = V3ScaleInv(*(const Vec3V*)&in[0], *(const FloatV*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V3Div(const float* in, float* out) { const Vec3V r = V3Div(*(const Vec3V*)&in[0], *(const Vec3V*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V3ScaleInvFast(const float* in, float* out) { const Vec3V r = V3ScaleInvFast(*(const Vec3V*)&in[0], *(const FloatV*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V3DivFast(const float* in, float* out) { const Vec3V r = V3DivFast(*(const Vec3V*)&in[0], *(const Vec3V*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V3Recip(const float* in, float* out) { const Vec3V r = V3Recip(*(const Vec3V*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V3RecipFast(const float* in, float* out) { const Vec3V r = V3RecipFast(*(const Vec3V*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V3Rsqrt(const float* in, float* out) { const Vec3V r = V3Rsqrt(*(const Vec3V*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V3RsqrtFast(const float* in, float* out) { const Vec3V r = V3RsqrtFast(*(const Vec3V*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V3ScaleAdd(const float* in, float* out) { const Vec3V r = V3ScaleAdd(*(const Vec3V*)&in[0], *(const FloatV*)&in[4], *(const Vec3V*)&in[8]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V3NegScaleSub(const float* in, float* out) { const Vec3V r = V3NegScaleSub(*(const Vec3V*)&in[0], *(const FloatV*)&in[4], *(const Vec3V*)&in[8]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V3MulAdd(const float* in, float* out) { const Vec3V r = V3MulAdd(*(const Vec3V*)&in[0], *(const Vec3V*)&in[4], *(const Vec3V*)&in[8]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V3NegMulSub(const float* in, float* out) { const Vec3V r = V3NegMulSub(*(const Vec3V*)&in[0], *(const Vec3V*)&in[4], *(const Vec3V*)&in[8]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V3Abs(const float* in, float* out) { const Vec3V r = V3Abs(*(const Vec3V*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V3Dot(const float* in, float* out) { const FloatV r = V3Dot(*(const Vec3V*)&in[0], *(const Vec3V*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V3Cross(const float* in, float* out) { const Vec3V r = V3Cross(*(const Vec3V*)&in[0], *(const Vec3V*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V3Length(const float* in, float* out) { const FloatV r = V3Length(*(const Vec3V*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V3LengthSq(const float* in, float* out) { const FloatV r = V3LengthSq(*(const Vec3V*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V3Normalize(const float* in, float* out) { const Vec3V r = V3Normalize(*(const Vec3V*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V3NormalizeSafe(const float* in, float* out) { const Vec3V r = V3NormalizeSafe(*(const Vec3V*)&in[0], *(const Vec3V*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V3SumElems(const float* in, float* out) { const FloatV r = V3SumElems(*(const Vec3V*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V3Sel(const float* in, float* out) { const Vec3V r = V3Sel(*(const BoolV*)&in[0], *(const Vec3V*)&in[4], *(const Vec3V*)&in[8]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V3IsGrtr(const float* in, float* out) { const BoolV r = V3IsGrtr(*(const Vec3V*)&in[0], *(const Vec3V*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V3IsGrtrOrEq(const float* in, float* out) { const BoolV r = V3IsGrtrOrEq(*(const Vec3V*)&in[0], *(const Vec3V*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V3IsEq(const float* in, float* out) { const BoolV r = V3IsEq(*(const Vec3V*)&in[0], *(const Vec3V*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V3Max(const float* in, float* out) { const Vec3V r = V3Max(*(const Vec3V*)&in[0], *(const Vec3V*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V3Min(const float* in, float* out) { const Vec3V r = V3Min(*(const Vec3V*)&in[0], *(const Vec3V*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V3ExtractMax(const float* in, float* out) { const FloatV r = V3ExtractMax(*(const Vec3V*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V3ExtractMin(const float* in, float* out) { const FloatV r = V3ExtractMin(*(const Vec3V*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V3Clamp(const float* in, float* out) { const Vec3V r = V3Clamp(*(const Vec3V*)&in[0], *(const Vec3V*)&in[4], *(const Vec3V*)&in[8]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V3Sign(const float* in, float* out) { const Vec3V r = V3Sign(*(const Vec3V*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V3AllGrtr(const float* in, float* out) { const uint32_t r = V3AllGrtr(*(const Vec3V*)&in[0], *(const Vec3V*)&in[4]); memcpy(out, &r, 4); }
extern "C" void px_V3AllGrtrOrEq(const float* in, float* out) { const uint32_t r = V3AllGrtrOrEq(*(const Vec3V*)&in[0], *(const Vec3V*)&in[4]); memcpy(out, &r, 4); }
extern "C" void px_V3AllEq(const float* in, float* out) { const uint32_t r = V3AllEq(*(const Vec3V*)&in[0], *(const Vec3V*)&in[4]); memcpy(out, &r, 4); }
extern "C" void px_V3OutOfBounds(const float* in, float* out) { const uint32_t r = V3OutOfBounds(*(const Vec3V*)&in[0], *(const Vec3V*)&in[4], *(const Vec3V*)&in[8]); memcpy(out, &r, 4); }
extern "C" void px_V3InBounds(const float* in, float* out) { const uint32_t r = V3InBounds(*(const Vec3V*)&in[0], *(const Vec3V*)&in[4], *(const Vec3V*)&in[8]); memcpy(out, &r, 4); }
extern "C" void px_V3Round(const float* in, float* out) { const Vec3V r = V3Round(*(const Vec3V*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V3Sin(const float* in, float* out) { const Vec3V r = V3Sin(*(const Vec3V*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V3Cos(const float* in, float* out) { const Vec3V r = V3Cos(*(const Vec3V*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V3PermYZZ(const float* in, float* out) { const Vec3V r = V3PermYZZ(*(const Vec3V*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V3PermXYX(const float* in, float* out) { const Vec3V r = V3PermXYX(*(const Vec3V*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V3PermYZX(const float* in, float* out) { const Vec3V r = V3PermYZX(*(const Vec3V*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V3PermZXY(const float* in, float* out) { const Vec3V r = V3PermZXY(*(const Vec3V*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V3PermZZY(const float* in, float* out) { const Vec3V r = V3PermZZY(*(const Vec3V*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V3PermYXX(const float* in, float* out) { const Vec3V r = V3PermYXX(*(const Vec3V*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V3Perm_Zero_1Z_0Y(const float* in, float* out) { const Vec3V r = V3Perm_Zero_1Z_0Y(*(const Vec3V*)&in[0], *(const Vec3V*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V3Perm_0Z_Zero_1X(const float* in, float* out) { const Vec3V r = V3Perm_0Z_Zero_1X(*(const Vec3V*)&in[0], *(const Vec3V*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V3Perm_1Y_0X_Zero(const float* in, float* out) { const Vec3V r = V3Perm_1Y_0X_Zero(*(const Vec3V*)&in[0], *(const Vec3V*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4Splat(const float* in, float* out) { const Vec4V r = V4Splat(*(const FloatV*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4Merge(const float* in, float* out) { const Vec4V r = V4Merge(*(const FloatV*)&in[0], *(const FloatV*)&in[4], *(const FloatV*)&in[8], *(const FloatV*)&in[12]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4MergeW(const float* in, float* out) { const Vec4V r = V4MergeW(*(const Vec4V*)&in[0], *(const Vec4V*)&in[4], *(const Vec4V*)&in[8], *(const Vec4V*)&in[12]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4MergeZ(const float* in, float* out) { const Vec4V r = V4MergeZ(*(const Vec4V*)&in[0], *(const Vec4V*)&in[4], *(const Vec4V*)&in[8], *(const Vec4V*)&in[12]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4MergeY(const float* in, float* out) { const Vec4V r = V4MergeY(*(const Vec4V*)&in[0], *(const Vec4V*)&in[4], *(const Vec4V*)&in[8], *(const Vec4V*)&in[12]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4MergeX(const float* in, float* out) { const Vec4V r = V4MergeX(*(const Vec4V*)&in[0], *(const Vec4V*)&in[4], *(const Vec4V*)&in[8], *(const Vec4V*)&in[12]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4UnpackXY(const float* in, float* out) { const Vec4V r = V4UnpackXY(*(const Vec4V*)&in[0], *(const Vec4V*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4UnpackZW(const float* in, float* out) { const Vec4V r = V4UnpackZW(*(const Vec4V*)&in[0], *(const Vec4V*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4UnitW(const float* in, float* out) { const Vec4V r = V4UnitW(); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4UnitY(const float* in, float* out) { const Vec4V r = V4UnitY(); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4UnitZ(const float* in, float* out) { const Vec4V r = V4UnitZ(); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4GetX(const float* in, float* out) { const FloatV r = V4GetX(*(const Vec4V*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4GetY(const float* in, float* out) { const FloatV r = V4GetY(*(const Vec4V*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4GetZ(const float* in, float* out) { const FloatV r = V4GetZ(*(const Vec4V*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4GetW(const float* in, float* out) { const FloatV r = V4GetW(*(const Vec4V*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4SetX(const float* in, float* out) { const Vec4V r = V4SetX(*(const Vec4V*)&in[0], *(const FloatV*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4SetY(const float* in, float* out) { const Vec4V r = V4SetY(*(const Vec4V*)&in[0], *(const FloatV*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4SetZ(const float* in, float* out) { const Vec4V r = V4SetZ(*(const Vec4V*)&in[0], *(const FloatV*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4SetW(const float* in, float* out) { const Vec4V r = V4SetW(*(const Vec4V*)&in[0], *(const FloatV*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4ClearW(const float* in, float* out) { const Vec4V r = V4ClearW(*(const Vec4V*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4ReadX(const float* in, float* out) { const float r = V4ReadX(*(const Vec4V*)&in[0]); memcpy(out, &r, 4); }
extern "C" void px_V4ReadY(const float* in, float* out) { const float r = V4ReadY(*(const Vec4V*)&in[0]); memcpy(out, &r, 4); }
extern "C" void px_V4ReadZ(const float* in, float* out) { const float r = V4ReadZ(*(const Vec4V*)&in[0]); memcpy(out, &r, 4); }
extern "C" void px_V4ReadW(const float* in, float* out) { const float r = V4ReadW(*(const Vec4V*)&in[0]); memcpy(out, &r, 4); }
extern "C" void px_V4Zero(const float* in, float* out) { const Vec4V r = V4Zero(); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4One(const float* in, float* out) { const Vec4V r = V4One(); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4Eps(const float* in, float* out) { const Vec4V r = V4Eps(); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4Neg(const float* in, float* out) { const Vec4V r = V4Neg(*(const Vec4V*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4Add(const float* in, float* out) { const Vec4V r = V4Add(*(const Vec4V*)&in[0], *(const Vec4V*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4Sub(const float* in, float* out) { const Vec4V r = V4Sub(*(const Vec4V*)&in[0], *(const Vec4V*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4Scale(const float* in, float* out) { const Vec4V r = V4Scale(*(const Vec4V*)&in[0], *(const FloatV*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4Mul(const float* in, float* out) { const Vec4V r = V4Mul(*(const Vec4V*)&in[0], *(const Vec4V*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4ScaleInv(const float* in, float* out) { const Vec4V r = V4ScaleInv(*(const Vec4V*)&in[0], *(const FloatV*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4Div(const float* in, float* out) { const Vec4V r = V4Div(*(const Vec4V*)&in[0], *(const Vec4V*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4ScaleInvFast(const float* in, float* out) { const Vec4V r = V4ScaleInvFast(*(const Vec4V*)&in[0], *(const FloatV*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4DivFast(const float* in, float* out) { const Vec4V r = V4DivFast(*(const Vec4V*)&in[0], *(const Vec4V*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4Recip(const float* in, float* out) { const Vec4V r = V4Recip(*(const Vec4V*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4RecipFast(const float* in, float* out) { const Vec4V r = V4RecipFast(*(const Vec4V*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4Rsqrt(const float* in, float* out) { const Vec4V r = V4Rsqrt(*(const Vec4V*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4RsqrtFast(const float* in, float* out) { const Vec4V r = V4RsqrtFast(*(const Vec4V*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4ScaleAdd(const float* in, float* out) { const Vec4V r = V4ScaleAdd(*(const Vec4V*)&in[0], *(const FloatV*)&in[4], *(const Vec4V*)&in[8]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4NegScaleSub(const float* in, float* out) { const Vec4V r = V4NegScaleSub(*(const Vec4V*)&in[0], *(const FloatV*)&in[4], *(const Vec4V*)&in[8]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4MulAdd(const float* in, float* out) { const Vec4V r = V4MulAdd(*(const Vec4V*)&in[0], *(const Vec4V*)&in[4], *(const Vec4V*)&in[8]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4NegMulSub(const float* in, float* out) { const Vec4V r = V4NegMulSub(*(const Vec4V*)&in[0], *(const Vec4V*)&in[4], *(const Vec4V*)&in[8]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4Abs(const float* in, float* out) { const Vec4V r = V4Abs(*(const Vec4V*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4Andc(const float* in, float* out) { const Vec4V r = V4Andc(*(const Vec4V*)&in[0], *(const VecU32V*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4Dot(const float* in, float* out) { const FloatV r = V4Dot(*(const Vec4V*)&in[0], *(const Vec4V*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4Dot3(const float* in, float* out) { const FloatV r = V4Dot3(*(const Vec4V*)&in[0], *(const Vec4V*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4Cross(const float* in, float* out) { const Vec4V r = V4Cross(*(const Vec4V*)&in[0], *(const Vec4V*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4Length(const float* in, float* out) { const FloatV r = V4Length(*(const Vec4V*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4LengthSq(const float* in, float* out) { const FloatV r = V4LengthSq(*(const Vec4V*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4Normalize(const float* in, float* out) { const Vec4V r = V4Normalize(*(const Vec4V*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4NormalizeSafe(const float* in, float* out) { const Vec4V r = V4NormalizeSafe(*(const Vec4V*)&in[0], *(const Vec4V*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4NormalizeFast(const float* in, float* out) { const Vec4V r = V4NormalizeFast(*(const Vec4V*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4Sel(const float* in, float* out) { const Vec4V r = V4Sel(*(const BoolV*)&in[0], *(const Vec4V*)&in[4], *(const Vec4V*)&in[8]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4IsGrtr(const float* in, float* out) { const BoolV r = V4IsGrtr(*(const Vec4V*)&in[0], *(const Vec4V*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4IsGrtrOrEq(const float* in, float* out) { const BoolV r = V4IsGrtrOrEq(*(const Vec4V*)&in[0], *(const Vec4V*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4IsEq(const float* in, float* out) { const BoolV r = V4IsEq(*(const Vec4V*)&in[0], *(const Vec4V*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4Max(const float* in, float* out) { const Vec4V r = V4Max(*(const Vec4V*)&in[0], *(const Vec4V*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4Min(const float* in, float* out) { const Vec4V r = V4Min(*(const Vec4V*)&in[0], *(const Vec4V*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4ExtractMax(const float* in, float* out) { const FloatV r = V4ExtractMax(*(const Vec4V*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4ExtractMin(const float* in, float* out) { const FloatV r = V4ExtractMin(*(const Vec4V*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4Clamp(const float* in, float* out) { const Vec4V r = V4Clamp(*(const Vec4V*)&in[0], *(const Vec4V*)&in[4], *(const Vec4V*)&in[8]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4AllGrtr(const float* in, float* out) { const uint32_t r = V4AllGrtr(*(const Vec4V*)&in[0], *(const Vec4V*)&in[4]); memcpy(out, &r, 4); }
extern "C" void px_V4AllGrtrOrEq(const float* in, float* out) { const uint32_t r = V4AllGrtrOrEq(*(const Vec4V*)&in[0], *(const Vec4V*)&in[4]); memcpy(out, &r, 4); }
extern "C" void px_V4AllGrtrOrEq3(const float* in, float* out) { const uint32_t r = V4AllGrtrOrEq3(*(const Vec4V*)&in[0], *(const Vec4V*)&in[4]); memcpy(out, &r, 4); }
extern "C" void px_V4AllEq(const float* in, float* out) { const uint32_t r = V4AllEq(*(const Vec4V*)&in[0], *(const Vec4V*)&in[4]); memcpy(out, &r, 4); }
extern "C" void px_V4AnyGrtr3(const float* in, float* out) { const uint32_t r = V4AnyGrtr3(*(const Vec4V*)&in[0], *(const Vec4V*)&in[4]); memcpy(out, &r, 4); }
extern "C" void px_V4Round(const float* in, float* out) { const Vec4V r = V4Round(*(const Vec4V*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4Sin(const float* in, float* out) { const Vec4V r = V4Sin(*(const Vec4V*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4Cos(const float* in, float* out) { const Vec4V r = V4Cos(*(const Vec4V*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4PermYXWZ(const float* in, float* out) { const Vec4V r = V4PermYXWZ(*(const Vec4V*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4PermXZXZ(const float* in, float* out) { const Vec4V r = V4PermXZXZ(*(const Vec4V*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4PermYWYW(const float* in, float* out) { const Vec4V r = V4PermYWYW(*(const Vec4V*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4PermYZXW(const float* in, float* out) { const Vec4V r = V4PermYZXW(*(const Vec4V*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4PermZWXY(const float* in, float* out) { const Vec4V r = V4PermZWXY(*(const Vec4V*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4Perm(const float* in, float* out) { const Vec4V r = V4Perm(*(const Vec4V*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_QuatV_From_RotationAxisAngle(const float* in, float* out) { const QuatV r = QuatV_From_RotationAxisAngle(*(const Vec3V*)&in[0], *(const FloatV*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_QuatNormalize(const float* in, float* out) { const QuatV r = QuatNormalize(*(const QuatV*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_QuatLength(const float* in, float* out) { const FloatV r = QuatLength(*(const QuatV*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_QuatLengthSq(const float* in, float* out) { const FloatV r = QuatLengthSq(*(const QuatV*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_QuatDot(const float* in, float* out) { const FloatV r = QuatDot(*(const QuatV*)&in[0], *(const QuatV*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_QuatConjugate(const float* in, float* out) { const QuatV r = QuatConjugate(*(const QuatV*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_QuatGetImaginaryPart(const float* in, float* out) { const Vec3V r = QuatGetImaginaryPart(*(const QuatV*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_QuatGetMat33V(const float* in, float* out) { const Mat33V r = QuatGetMat33V(*(const QuatV*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_Mat33GetQuatV(const float* in, float* out) { const QuatV r = Mat33GetQuatV(*(const Mat33V*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_QuatGetBasisVector0(const float* in, float* out) { const Vec3V r = QuatGetBasisVector0(*(const QuatV*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_QuatGetBasisVector1(const float* in, float* out) { const Vec3V r = QuatGetBasisVector1(*(const QuatV*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_QuatGetBasisVector2(const float* in, float* out) { const Vec3V r = QuatGetBasisVector2(*(const QuatV*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_QuatRotate(const float* in, float* out) { const Vec3V r = QuatRotate(*(const QuatV*)&in[0], *(const Vec3V*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_QuatRotateInv(const float* in, float* out) { const Vec3V r = QuatRotateInv(*(const QuatV*)&in[0], *(const Vec3V*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_QuatMul(const float* in, float* out) { const QuatV r = QuatMul(*(const QuatV*)&in[0], *(const QuatV*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_QuatAdd(const float* in, float* out) { const QuatV r = QuatAdd(*(const QuatV*)&in[0], *(const QuatV*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_QuatNeg(const float* in, float* out) { const QuatV r = QuatNeg(*(const QuatV*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_QuatSub(const float* in, float* out) { const QuatV r = QuatSub(*(const QuatV*)&in[0], *(const QuatV*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_QuatScale(const float* in, float* out) { const QuatV r = QuatScale(*(const QuatV*)&in[0], *(const FloatV*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_QuatMerge(const float* in, float* out) { const QuatV r = QuatMerge(*(const FloatV*)&in[0], *(const FloatV*)&in[4], *(const FloatV*)&in[8], *(const FloatV*)&in[12]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_QuatIdentity(const float* in, float* out) { const QuatV r = QuatIdentity(); memcpy(out, &r, sizeof(r)); }
extern "C" void px_isFiniteQuatV(const float* in, float* out) { const float r = isFiniteQuatV(*(const QuatV*)&in[0]) ? 1.0f : 0.0f; memcpy(out, &r, 4); }
extern "C" void px_isValidQuatV(const float* in, float* out) { const float r = isValidQuatV(*(const QuatV*)&in[0]) ? 1.0f : 0.0f; memcpy(out, &r, 4); }
extern "C" void px_isSaneQuatV(const float* in, float* out) { const float r = isSaneQuatV(*(const QuatV*)&in[0]) ? 1.0f : 0.0f; memcpy(out, &r, 4); }
extern "C" void px_BFFFF(const float* in, float* out) { const BoolV r = BFFFF(); memcpy(out, &r, sizeof(r)); }
extern "C" void px_BFFFT(const float* in, float* out) { const BoolV r = BFFFT(); memcpy(out, &r, sizeof(r)); }
extern "C" void px_BFFTF(const float* in, float* out) { const BoolV r = BFFTF(); memcpy(out, &r, sizeof(r)); }
extern "C" void px_BFFTT(const float* in, float* out) { const BoolV r = BFFTT(); memcpy(out, &r, sizeof(r)); }
extern "C" void px_BFTFF(const float* in, float* out) { const BoolV r = BFTFF(); memcpy(out, &r, sizeof(r)); }
extern "C" void px_BFTFT(const float* in, float* out) { const BoolV r = BFTFT(); memcpy(out, &r, sizeof(r)); }
extern "C" void px_BFTTF(const float* in, float* out) { const BoolV r = BFTTF(); memcpy(out, &r, sizeof(r)); }
extern "C" void px_BFTTT(const float* in, float* out) { const BoolV r = BFTTT(); memcpy(out, &r, sizeof(r)); }
extern "C" void px_BTFFF(const float* in, float* out) { const BoolV r = BTFFF(); memcpy(out, &r, sizeof(r)); }
extern "C" void px_BTFFT(const float* in, float* out) { const BoolV r = BTFFT(); memcpy(out, &r, sizeof(r)); }
extern "C" void px_BTFTF(const float* in, float* out) { const BoolV r = BTFTF(); memcpy(out, &r, sizeof(r)); }
extern "C" void px_BTFTT(const float* in, float* out) { const BoolV r = BTFTT(); memcpy(out, &r, sizeof(r)); }
extern "C" void px_BTTFF(const float* in, float* out) { const BoolV r = BTTFF(); memcpy(out, &r, sizeof(r)); }
extern "C" void px_BTTFT(const float* in, float* out) { const BoolV r = BTTFT(); memcpy(out, &r, sizeof(r)); }
extern "C" void px_BTTTF(const float* in, float* out) { const BoolV r = BTTTF(); memcpy(out, &r, sizeof(r)); }
extern "C" void px_BTTTT(const float* in, float* out) { const BoolV r = BTTTT(); memcpy(out, &r, sizeof(r)); }
extern "C" void px_BWMask(const float* in, float* out) { const BoolV r = BWMask(); memcpy(out, &r, sizeof(r)); }
extern "C" void px_BXMask(const float* in, float* out) { const BoolV r = BXMask(); memcpy(out, &r, sizeof(r)); }
extern "C" void px_BYMask(const float* in, float* out) { const BoolV r = BYMask(); memcpy(out, &r, sizeof(r)); }
extern "C" void px_BZMask(const float* in, float* out) { const BoolV r = BZMask(); memcpy(out, &r, sizeof(r)); }
extern "C" void px_BGetX(const float* in, float* out) { const BoolV r = BGetX(*(const BoolV*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_BGetY(const float* in, float* out) { const BoolV r = BGetY(*(const BoolV*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_BGetZ(const float* in, float* out) { const BoolV r = BGetZ(*(const BoolV*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_BGetW(const float* in, float* out) { const BoolV r = BGetW(*(const BoolV*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_BAnd(const float* in, float* out) { const BoolV r = BAnd(*(const BoolV*)&in[0], *(const BoolV*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_BOr(const float* in, float* out) { const BoolV r = BOr(*(const BoolV*)&in[0], *(const BoolV*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_BNot(const float* in, float* out) { const BoolV r = BNot(*(const BoolV*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_BAllTrue4(const float* in, float* out) { const BoolV r = BAllTrue4(*(const BoolV*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_BAnyTrue4(const float* in, float* out) { const BoolV r = BAnyTrue4(*(const BoolV*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_BAllTrue3(const float* in, float* out) { const BoolV r = BAllTrue3(*(const BoolV*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_BAnyTrue3(const float* in, float* out) { const BoolV r = BAnyTrue3(*(const BoolV*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_BAllEq(const float* in, float* out) { const uint32_t r = BAllEq(*(const BoolV*)&in[0], *(const BoolV*)&in[4]); memcpy(out, &r, 4); }
extern "C" void px_BAllEqTTTT(const float* in, float* out) { const uint32_t r = BAllEqTTTT(*(const BoolV*)&in[0]); memcpy(out, &r, 4); }
extern "C" void px_BAllEqFFFF(const float* in, float* out) { const uint32_t r = BAllEqFFFF(*(const BoolV*)&in[0]); memcpy(out, &r, 4); }
extern "C" void px_VecI32V_Zero(const float* in, float* out) { const VecI32V r = VecI32V_Zero(); memcpy(out, &r, sizeof(r)); }
extern "C" void px_VecI32V_One(const float* in, float* out) { const VecI32V r = VecI32V_One(); memcpy(out, &r, sizeof(r)); }
extern "C" void px_VecI32V_Two(const float* in, float* out) { const VecI32V r = VecI32V_Two(); memcpy(out, &r, sizeof(r)); }
extern "C" void px_VecI32V_MinusOne(const float* in, float* out) { const VecI32V r = VecI32V_MinusOne(); memcpy(out, &r, sizeof(r)); }
extern "C" void px_VecI32V_Add(const float* in, float* out) { const VecI32V r = VecI32V_Add(*(const VecI32V*)&in[0], *(const VecI32V*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_VecI32V_Or(const float* in, float* out) { const VecI32V r = VecI32V_Or(*(const VecI32V*)&in[0], *(const VecI32V*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_VecI32V_GetX(const float* in, float* out) { const VecI32V r = VecI32V_GetX(*(const VecI32V*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_VecI32V_GetY(const float* in, float* out) { const VecI32V r = VecI32V_GetY(*(const VecI32V*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_VecI32V_GetZ(const float* in, float* out) { const VecI32V r = VecI32V_GetZ(*(const VecI32V*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_VecI32V_GetW(const float* in, float* out) { const VecI32V r = VecI32V_GetW(*(const VecI32V*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_VecI32V_Sub(const float* in, float* out) { const VecI32V r = VecI32V_Sub(*(const VecI32V*)&in[0], *(const VecI32V*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_VecI32V_IsGrtr(const float* in, float* out) { const BoolV r = VecI32V_IsGrtr(*(const VecI32V*)&in[0], *(const VecI32V*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_VecI32V_IsEq(const float* in, float* out) { const BoolV r = VecI32V_IsEq(*(const VecI32V*)&in[0], *(const VecI32V*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_U4Zero(const float* in, float* out) { const VecU32V r = U4Zero(); memcpy(out, &r, sizeof(r)); }
extern "C" void px_U4One(const float* in, float* out) { const VecU32V r = U4One(); memcpy(out, &r, sizeof(r)); }
extern "C" void px_U4Two(const float* in, float* out) { const VecU32V r = U4Two(); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4IsEqU32(const float* in, float* out) { const BoolV r = V4IsEqU32(*(const VecU32V*)&in[0], *(const VecU32V*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4U32or(const float* in, float* out) { const VecU32V r = V4U32or(*(const VecU32V*)&in[0], *(const VecU32V*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4U32xor(const float* in, float* out) { const VecU32V r = V4U32xor(*(const VecU32V*)&in[0], *(const VecU32V*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4U32and(const float* in, float* out) { const VecU32V r = V4U32and(*(const VecU32V*)&in[0], *(const VecU32V*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4U32Andc(const float* in, float* out) { const VecU32V r = V4U32Andc(*(const VecU32V*)&in[0], *(const VecU32V*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_V4IsGrtrV32u(const float* in, float* out) { const VecU32V r = V4IsGrtrV32u(*(const Vec4V*)&in[0], *(const Vec4V*)&in[4]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_M33MulV3(const float* in, float* out) { const Vec3V r = M33MulV3(*(const Mat33V*)&in[0], *(const Vec3V*)&in[16]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_M33MulV3AddV3(const float* in, float* out) { const Vec3V r = M33MulV3AddV3(*(const Mat33V*)&in[0], *(const Vec3V*)&in[16], *(const Vec3V*)&in[20]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_M33TrnspsMulV3(const float* in, float* out) { const Vec3V r = M33TrnspsMulV3(*(const Mat33V*)&in[0], *(const Vec3V*)&in[16]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_M33MulM33(const float* in, float* out) { const Mat33V r = M33MulM33(*(const Mat33V*)&in[0], *(const Mat33V*)&in[16]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_M33Add(const float* in, float* out) { const Mat33V r = M33Add(*(const Mat33V*)&in[0], *(const Mat33V*)&in[16]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_M33Sub(const float* in, float* out) { const Mat33V r = M33Sub(*(const Mat33V*)&in[0], *(const Mat33V*)&in[16]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_M33Neg(const float* in, float* out) { const Mat33V r = M33Neg(*(const Mat33V*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_M33Abs(const float* in, float* out) { const Mat33V r = M33Abs(*(const Mat33V*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_M33Inverse(const float* in, float* out) { const Mat33V r = M33Inverse(*(const Mat33V*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_M33Trnsps(const float* in, float* out) { const Mat33V r = M33Trnsps(*(const Mat33V*)&in[0]); memcpy(out, &r, sizeof(r)); }
extern "C" void px_M33Identity(const float* in, float* out) { const Mat33V r = M33Identity(); memcpy(out, &r, sizeof(r)); }
